version: 1
disable_existing_loggers: false

formatters:
  default:
    (): colorlog.ColoredFormatter
    format: "%(log_color)s[%(levelname)s] [%(asctime)s] [%(filename)s:%(lineno)d] %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
    log_colors:
      DEBUG:    cyan
      INFO:     green
      WARNING:  yellow
      ERROR:    red
      CRITICAL: bold_red

handlers:
  console:
    class: logging.StreamHandler
    stream: ext://sys.stdout
    level: INFO
    formatter: default

loggers:
  "":                { handlers: [console], level: INFO, propagate: false }
  uvicorn:           { handlers: [console], level: INFO, propagate: false }
  uvicorn.error:     { handlers: [console], level: INFO, propagate: false }
  uvicorn.access:    { handlers: [console], level: INFO, propagate: false }
