"""0002 create tenant table

Revision ID: 4358ecb3e980
Revises: 6030d4c779ae
Create Date: 2025-11-10 21:36:56.768162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4358ecb3e980'
down_revision: Union[str, None] = '6030d4c779ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'tenant', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tenant', type_='unique')
    # ### end Alembic commands ###
